backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:

  - name: "products"
    label: "Products"
    file: "products/products.json"

    fields:

      - {label: "Product ID", name: "id", widget: "number"}

      - {label: "Product Name", name: "name", widget: "string"}

      - {label: "Price", name: "price", widget: "number"}

      - {label: "Description", name: "description", widget: "text"}

      - label: "Images"
        name: "images"
        widget: "list"
        field: {label: Image, name: image, widget: image}